package main

import "fmt"

func main(){
    fmt.Println("\n\n\n           Merhaba\n")
    fmt.Println("                              ``````.''`                                   ")
    fmt.Println("                            .=in}c?xhbdWVr_                                ")
    fmt.Println("                          '^VUwtn]v]nnzaW0$mr                              ")
    fmt.Println("                        `\"}UVx(?r^<<<*?ilJKd$U\"                          ")
    fmt.Println("                       -:iV]v|?*^<~~>*r?|x}nsGb~                           ")
    fmt.Println("                      .:v}x]]]?*^<~>^^*rvx}cVcVO*                          ")
    fmt.Println("                     `-=i]]}]i?*^^^<^**?|v]nyn]d8=                         ")
    fmt.Println("                     -,^}}xixi(*<~~~~>^rvcsXtzl6#Z.                        ")
    fmt.Println("                     -=}liiV6ZUmmV|**izSZPmbanj6##]                        ")
    fmt.Println("                     '^j]vv}jaqZPt]^^zVVjqZPVlVKg#H'                       ")
    fmt.Println("                     'rUV](r|i}]v??**c(*?v(r?}wP6Qh-                       ")
    fmt.Println("                     ,?Uj}vr^<!!~*r>~i]r!=!riVXm$Dr`                       ")
    fmt.Println("                     'riiii?r^^(v|r<!inz(^^|nVV2p]_                        ")
    fmt.Println("                      ,(>(xrrrxVyKSP5RgOj]](]njj?-                         ")
    fmt.Println("                      `*~~li**XPKUXVyaS6dSml}wh?`                          ")
    fmt.Println("                       -=:xn(*l(ix]]nnn2V}n]nU}.                           ")
    fmt.Println("                       `,!*}nJ}ilnV}]]nVV}VttU^                            ")
    fmt.Println("                      `,]z=?VqKjlvv]((]}lwdHhq]_                           ")
    fmt.Println("                '!?}wb8B#D<nmqZmKUjjVnVwKWSjt5##8Pn|!`                     ")
    fmt.Println("          `=(V5g#@@@@###@#i^tozyehmPqHPUhynVlvb#@@@@@#Q6Un|~-`             ")
    fmt.Println("     `>lSg#@@@@@@@@@@#@@@@ZvV}v?v]lnnVu]]]ul*^*$@@@@@@@@@@@@@#QX-          ")
    fmt.Println("    rB@##@@@@@@@@@@@@@@@@@@ZW]V?^?vviv??}J}rrr>v#@@@@@@@@@@@@@@@8!         ")
    fmt.Println("   'd#@@@@@@@@@@@#@@@@@@@@@#pv}n?r(??rr}cr>~!=!e#@@@@@@@@@@@@@@@@#~        ")
    fmt.Println("   v@@@@@@@@@@@@@#@@@@@@@@@@@P?r|r*^<^||!~!=::z@@@@@@@@@@@@@@@@@@@B=       ")
    fmt.Println("  `b@@@@@@@@@#@@@@#@@@@@@@@@@#irvvr^^r^=<^!!*E@@@@@@@@@@@@@@@@@@@@@$'      ")
    fmt.Println("  !#@@@@@@@@@@@@@@@@@@@@@@@@@@p<!?(?r*=!<rub#@@@@@@@@@@@@@@@@@@@@@@@V      ")
    fmt.Println("  r@@@@@@@@@@@@@@@@@@@@@@@@@@@#z::<(i*:^Z#@@@@@@@@@@@@@@@@@@@@@@@@@@#,     ")
    fmt.Println(" 'q@@@@@@@@@@@@#@@@#@@@@@@@@@@@B?:,!?~rq@@@@@@@@@@@@@@@@@@@@@@@@@@@@@]     ")
    fmt.Println(" -6@@@@@@@@@@@@@@@@#@@@@@@@@@@@@gr!:>nx8@@@@@@@@@@@@@@@@#@@@@@@@@@@@@#~    ")
    fmt.Println("  m@@@@@@@@@@@@@@@@#@@@@@@@@@@@@@t~~i}x#@@@@@@@@@@@@@@@#@@@@@@@@@@@@@@}    ")
    fmt.Println("  X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g?(v<2@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@E`   ")
    fmt.Println("  }@@@@@@@@@@@@@@@@##@@@@@@@@@@@@#cv^=Z@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(   ")
    fmt.Println("  ^#@@@@@@@@@@@@@Q#####@@@@@@@@@@#R?~~g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@m   ")
    fmt.Println("  =#@@@@@@@@@@@@@8#######@@@@@@@@##u~*B@@@@@@@@@@#8dUXZB@@@@@@@@@@@@@@@#,  ")
    fmt.Println("  'N@@@@@@@@@@@@@@@@@@@@@@@@@@@###@#QB##@@#####Klr^<~!~}####@@@@@@@@@@@#:  ")
    fmt.Println("   v#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#@@@@@@@@@@5=:~^*r?}##@##@@@@@@@@@@@?  ")
    fmt.Println("   ,B@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@##@@@@@@@@@@R!==r?x]}g#@@@@@@@@@@@@@@i  ")
    fmt.Println("    2@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#@@@@@@@@@@@@g^~~]a0##@@@@@@@@@@@@@@@@h  ")
    fmt.Println("    '6@@@@@@@@@@@@@@@@@@@@@@@@@@@#@@@@@@@@@@@@@$]ud#@@@@@@@@@@@@@@#@@@@@s  ")
    fmt.Println("     _0@@@@@@@@@@@@@@@@@@@@@@@@@@@#############B#@@@@@@@@@@@@@@@@@@@@@@@(  ")
    fmt.Println("      _R@@@@@@@#######@@@@@@@####B880gN8gQ######B#####@@@@@@@@@@@@@@@@@#!  ")
    fmt.Println("\n\n           Merhaba ben Volkan Konak\n\n\n\n")
}